### PR TITLE
Sync Gtilde speedup

### PR DESCRIPTION
**Pull request by tibaldo**
This simple mod speed up the calculation of synchrotron spectra by 40%. See discussion in #135.

### CODE REVIEW

**Comment by zblz** [comment]
Can you rebase on master so that only the last commit (03a4ae4) remains in the PR? The first two are already in master and the merge commit introduces conflicts in `travis.yml`.

**Comment by tibaldo** [comment]
There is a conflict I cannot resolve in any way, I'll start clean with another branch.

**Comment by zblz** [comment]
I see you created a new PR, but for the record this could have been resolved with `git rebase -i origin/master` and then dropping the first couple of commits. After rewriting the branch you have to force push to update

**Comment by tibaldo** [comment]
I tried to do this, but the rebase was failing due to non-mergeable conflicts in .travis.yaml that I could not figure out how to resolve (although they seemed relatively trivial).
Anyway, sorry for the example of bad practises, but I got frustrated and it was way faster to do the new PR.

**Pull request closed without merging**
